# seed data
words_data = {
    "dog": "🐶",
    "cat": "🐱",
    "duck": "🦆",
    "pig": "🐖",
    "zebra": "🦓",
    "frog": "🐸",
    "bird": "🐦",
    "horse": "🐴",
    "crab": "🦀",
    "shark": "🦈",
    "fox": "🦊",
    "ant": "🐜",
    "unicorn": "🦄",
    "turtle": "🐢",
    "dragon": "🐉",
    "butterfly": "🦋",
    "cow": "🐮",
    "ladybug": "🐞",
    "worm": "🪱",
    "sun": "🌞",
    "moon": "🌚",
    "star": "⭐️",
    "fire": "🔥",
    "kiwi": "🥝",
    "egg": "🥚",
    "cookie": "🍪",
    "apple": "🍎",
    "donut": "🍩",
    "cake": "🎂",
    "popcorn": "🍿",
    "corn": "🌽",
    "lemon": "🍋",
    "bacon": "🥓",
    "hotdog": "🌭",
    "candy": "🍬",
}
