# seed data
words_data = {
    "dog": "🐶",
    "cat": "🐱",
    "duck": "🦆",
    "pig": "🐖",
    "zebra": "🦓",
    "frog": "🐸",
    "bird": "🐦",
    "horse": "🐴",
    "crab": "🦀",
    "worm": "🪱",
    "sun": "🌞",
    "egg": "🥚",
    "cookie": "🍪",
    "apple": "🍎",
    "donut": "🍩",
    "cake": "🎂",
    "popcorn": "🍿",
    "corn": "🌽",
    "lemon": "🍋",
    "bacon": "🥓",
    "hotdog": "🌭",
    "candy": "🍬",
}
